### ISSUE TITLE
The Slack is Private

### ISSUE THREAD

**Issue by grahamc** [tpm2-software/tpm2-software.github.io#63]
Hello,

It looks like the Slack instance requires being employed by Intel Infineon or some other random company. Is this on purpose? Is it supposed to be a community thing?

Thanks!

**Comment by AndreasFuchsSIT** [comment]
Ok, I removed the slack-info. Noone actually uses it.

**Comment by williamcroberts** [comment]
Thanks, that was something I was meaning to look into and do.
________________________________
