### ISSUE TITLE
migrate to libera.chat/oftc.net IRC server instead of freenode.net

### ISSUE THREAD

**Issue by mrkz** [tpm2-software/tpm2-software.github.io#68]
Hi,

I'm just wondering if the main communication channel for IRC is happening on the freenode.net server or if this page should refer to libera.chat IRC server instead (like most FLOSS projects have moved to as well).

**Comment by AndreasFuchsSIT** [comment]
I wonder if anyone is actually still logged in, since we have gitter
@williamcroberts @idesai your thoughts ?
I'm not on IRC to begin with...

**Comment by williamcroberts** [comment]
I don't use any of these real time chat services

**Comment by diabonas** [comment]
I idle in `#tpm2.0-tss` on Libera Chat, but it is petty quiet (currently it has five users and maybe one message per month). No idea about Freenode, I think it is pretty much dead by now. If in doubt, I would just remove the reference to the IRC channel altogether and redirect people to Gitter instead (which can be accessed [over the IRC protocol as well](https://irc.gitter.im/)).
